name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk
    steps:
      - uses: actions/checkout@v4
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build with Maven
        run: ./mvnw clean compile test package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: ./target/*.jar